//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LtkdKhoa
    {
        public string LtkdMaKH { get; set; }
        public string LtkdTenKH { get; set; }
        public bool LtkdTrangThai { get; set; }
    }
}
