//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LtkdSinhVien
    {
        public string LtkdMaSV { get; set; }
        public string LtkdHoSV { get; set; }
        public string LtkdTenSV { get; set; }
        public Nullable<System.DateTime> LtkdNgaySinh { get; set; }
        public Nullable<bool> LtkdPhai { get; set; }
        public string LtkdPhone { get; set; }
        public string LtkdEmail { get; set; }
        public string LtkdMaKH { get; set; }
    }
}
